### ISSUE TITLE
Add MIT License file

### ISSUE THREAD

**Issue by andygup** [download-directory/download-directory.github.io#102]
Great job on this repo! Would it be possible to add an MIT license file along with a link to it in the README? Here's an informative blog post: https://fossa.com/blog/open-source-licenses-101-mit-license/

**Comment by HeetVekariya** [comment]
If this is valid issue, then i would like work on this issue. Please assign it to me.

**Comment by andygup** [comment]
Okay, thanks @HeetVekariya. Yes, this request is based on licensing best practices.

**Comment by HeetVekariya** [comment]
Can you please assign this issue to me

**Comment by fregante** [comment]
Done
