### ISSUE TITLE
Filenames with spaces

### ISSUE THREAD

**Issue by abranhe** [download-directory/download-directory.github.io#11]
After regenerating a new token for [download-directory](https://github.com/download-directory), I tried to download a directory from a repository, but it seems to download any files.

![Screenshot](https://cdn.abranhe.com/issues/download-directory/screenshot.png)

When I try to unzip the file, since there wasn't files inside, it shows a warning

![Warning](https://cdn.abranhe.com/issues/download-directory/warning.png)

> I checked multiple times: 😂there were files on the repo!

- Is there any way to solve this?
- Is this issue caused by a wrong setup of Github token?
- Is this even a valid issue, or am I just doing it wrong?

**Comment by bfred-it** [comment]
Is it a private repo? Can you check the console for further messages?

**Comment by abranhe** [comment]
No, it isn't a private repo. I have tried in multiple browsers and the same issue in all of them. Take a look at the console:

<img width="1103" alt="isssue-with-console" src="https://user-images.githubusercontent.com/21347264/46050367-c4761080-c101-11e8-9130-60d27ed6ed93.png">

I have used **download-directory** before with **refined-github**, and it worked perfectly fine, but I have recently regenerated the token, and after that I am facing that issue.

**Comment by bfred-it** [comment]
If you paste the full URL I’ll give it a go

**Comment by abranhe** [comment]
I guess, I figured it out what the problem is:

When you try to donwload any directory that have any blank space `" "` on it like so:

```
├── programming books
    ├── The C Programming
    ├── Clean Code
├── other-books
    ├── The Titanic
    ├── The beauty and the beast
```

If you try to donwload the `programming books` directory you won't be able to do it and you will have the same issue I had (**Downloaded 0 files**), since `programming books` has that blank space (`" "`).

But insted, if you try to download the `other-books` directory you will be able to donwload it perfectly ok. So I guess we have discovered a **bug**. 🐞

**Comment by bfred-it** [comment]
Another small example: https://github.com/iaolo/iA-Fonts/tree/master/iA%20Writer%20Duospace/OTF%20(Mac)

PRs welcome

**Comment by loilo** [comment]
I just stumbled upon the exact same files to download (the iA Writer Duospace fonts). The issue is the URL-encoded characters, it should be a rather quick fix. I'll give it a try. 🙂
