### ISSUE TITLE
Browser reporting the website as a virus

### ISSUE THREAD

**Issue by bannmannutt** [download-directory/download-directory.github.io#112]
Exactly what it says on the tin
![bookmark](https://github.com/download-directory/download-directory.github.io/assets/25557538/d7ed0046-a7a4-4415-bde9-6864e978ef41)

**Comment by fregante** [comment]
Ugh someone probably used it as a redirect to download stuff from GitHub and it got reported.

Thanks for the report, let me see if I can take it off it.

**Comment by fregante** [comment]
I can't repro: https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fdownload-directory.github.io%2F&hl=en

Do you have any antivirus or virus installed? 😅

**Comment by fregante** [comment]
Ok here it is:

<img width="579" alt="Screenshot" src="https://github.com/download-directory/download-directory.github.io/assets/1402241/b776cdad-9789-4e27-b07a-a3c1e18f009e">

**Comment by fregante** [comment]
I reverse-reported it, let's hope for the best:

> The page is hosted on GitHub and is composed of a handful of files used to download from another repo. This acts similarly to a redirect website, it doesn't host anything.
>
> Please contact me on the repo if there's anything I can do to fix this issue.
>
> See the entirety of the website here: https://github.com/download-directory/download-directory.github.io/tree/gh-pages


https://safebrowsing.google.com/safebrowsing/report_error/?hl=en

**Comment by fregante** [comment]
The check page has also been updated yesterday :(

<img width="1203" alt="Screenshot" src="https://github.com/download-directory/download-directory.github.io/assets/1402241/b6995d9a-6946-4512-9496-78caa90e6c11">

**Comment by fregante** [comment]
Some a-h reported this 🤦‍♂️ 

<img width="964" alt="Screenshot 6" src="https://github.com/download-directory/download-directory.github.io/assets/1402241/4abc6707-2e0f-402d-afbf-cbfe37588110">

and it's on all browsers now

<img width="753" alt="Screenshot 7" src="https://github.com/download-directory/download-directory.github.io/assets/1402241/4a8d9816-813e-4b1b-ba75-142b530fc0f4">

I filed an appeal

**Comment by fregante** [comment]
> To: Webmaster of https://download-directory.github.io/,
> 
> Google has received and processed your security review request. Google systems indicate that https://download-directory.github.io/ no longer contains links to harmful sites or downloads. **The warnings visible to users are being removed from your site. This may take a few hours to happen.**

Thank you for reporting!

**Comment by fregante** [comment]
I'm seeing this again in the search console, but not when opening the website yet.

<img width="854" alt="Screenshot 2" src="https://github.com/user-attachments/assets/4dba4bcc-ac8c-4cf6-8601-dd71cc40e6a2">



This time there's no sample URL 🤷‍♂️
