### ISSUE TITLE
LFS Support for files with spaces

### ISSUE THREAD

**Issue by CrackHub** [download-directory/download-directory.github.io#114]
Can we have lfs support?
https://github.com/EpsilonsQc/Final-Survivors/blob/1c0e844fc06090cb7f8028b0df13c0c550af2610/Assets/External/Robots%20Ultimate%20Pack%2002%20Cute%20Series/Spider%20Queen%20Robot%20Cute%20Series/Textures/Spider%20Queen%20Robot%20Emission.psd

**Comment by fregante** [comment]
Are you pasting that URL or the directory? We added LFS support this year: 

- https://github.com/download-directory/download-directory.github.io/pull/106

**Comment by CrackHub** [comment]
I try this and psd files coming with 0 kb
https://github.com/EpsilonsQc/Final-Survivors/tree/1c0e844fc06090cb7f8028b0df13c0c550af2610/Assets/External/Robots%20Ultimate%20Pack%2002%20Cute%20Series/Spider%20Queen%20Robot%20Cute%20Series/Textures

**Comment by fregante** [comment]
I think the issue is the spaces, the LFS URL generated points to a 404

https://media.githubusercontent.com/media/EpsilonsQc/Final-Survivors/1c0e844fc06090cb7f8028b0df13c0c550af2610/Assets/External/Robots%20Ultimate%20Pack%2002%20Cute%20Series/Spider%20Queen%20Robot%20Cute%20Series/Textures/Spider%20Queen%20Robot%20Emission.psd

**Comment by fregante** [comment]
@FoxRefire do you have any ideas on how to fix this?

**Comment by FoxRefire** [comment]
This is unfixable.
If the LFS is functioning properly, the API will return a URL starting with `https://media.` for the value of download_url, as follows:
https://api.github.com/repos/jgarside1678/T9/contents/Content/Units/Alliance/Animations/MageAnimationSet/Animations/InPlace/Mage_Beam_2h_End_IP.uasset

However, in this case, even though LFS is used, it does not return the correct URL.
https://api.github.com/repos/EpsilonsQc/Final-Survivors/contents/Assets/External/Robots Ultimate Pack 02 Cute Series/Cute series demo assets/Roboti Ground.psd

So, I tried cloning the entire repository as a test, and the following error was returned.
```
Error downloading object: Assets/External/CUBE - Abandoned Base/FBX/Barrel 01.fbx (dd038ab): Smudge error: Error downloading Assets/External/CUBE - Abandoned Base/FBX/Barrel 01.fbx (dd038abc9940d0ecfc729be32590301bd9bbbdd8ff5c3487d225f03b98495d04): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```
The error indicates that the repository has exceeded its LFS data quota, which has been disabled, and the file cannot be retrieved even if a `git clone` is used.

It is impossible to download files unless the repository owner fixes this problem.

**Comment by fregante** [comment]
@FoxRefire thank you for looking into it!
