### ISSUE TITLE
zipfile contains folder of parent level

### ISSUE THREAD

**Issue by topic2k** [download-directory/download-directory.github.io#12]
I wanted to download folder `waynes_world` from https://github.com/j2labs/zmq_examples. The created zip-file also contained the complete folder `waynes_world_2`, which is not a content of folder `waynes_world`.

**Comment by fregante** [comment]
Indeed, this is due to both folders starting with `waynes_world`. It's been fixed in https://github.com/fregante/list-github-dir-content/releases/tag/v1.1.1

**Comment by topic2k** [comment]
Thank you for fixing it.
