### ISSUE TITLE
Stuck on "Zipping"

### ISSUE THREAD

**Issue by CosMo578** [download-directory/download-directory.github.io#133]
When ever I am trying to download a file it get stuck at Zipping n file, and the download does not start
![Screenshot from 2024-07-25 07-01-23](https://github.com/user-attachments/assets/73ca9719-a8ec-4322-87a3-bd498711b5be)

**Comment by fregante** [comment]
What browser are you using?

**Comment by fregante** [comment]
https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FCosMo578%2Fastro-course-demo%2Ftree%2Fmain%2Fpublic%2Fimages

The file downloads successfully, but the page isn't updated:

<img width="842" alt="Screenshot 3" src="https://github.com/user-attachments/assets/ce6affff-e1bd-455e-a814-366d05387848">

I'll open a separate issue to update the UI

**Comment by fregante** [comment]
It's due to 

https://github.com/dy/save-file/blob/1019565509e421ff82dd1eaf8282828ad4133ae4/browser.js#L42-L46

**Comment by fregante** [comment]
Fixed 🙏 thanks for the report
