### ISSUE TITLE
Downloading from tags broken

### ISSUE THREAD

**Issue by he3als** [download-directory/download-directory.github.io#135]
It would be helpful if downloading from tags worked, e.g. https://github.com/Atlas-OS/Atlas/tree/0.4.0/src/playbook/Executables/AtlasDesktop

**Comment by fregante** [comment]
That's curious, there shouldn't be any reason why it shouldn't work. I probably broke it recently

**Comment by he3als** [comment]
![image](https://github.com/user-attachments/assets/aa54d577-0974-4df3-b325-019c2d086319)

```json
{
  "message": "Branch not found",
  "documentation_url": "https://docs.github.com/rest/branches/branches#get-a-branch",
  "status": "404"
}
```

From what I can see in DevTools, something with the GitHub API might've changed. I'm not sure though

**Comment by fregante** [comment]
I see the problem: 

https://github.com/download-directory/download-directory.github.io/blob/e934a2847242ebd0369fd602072756e5dd180d6e/repository-info.ts#L102

It shouldn't check whether the branch exists, but whether the *git reference* exists. 

PR welcome to change API

**Comment by fregante** [comment]
- broken in https://github.com/download-directory/download-directory.github.io/pull/124/files
