### ISSUE TITLE
`rgh-linkify-features` - Restore

### ISSUE THREAD

**Issue by kovsu** [download-directory/download-directory.github.io#143]
`rgh-linkify-features`

**Comment by kovsu** [comment]
https://github.com/

**Comment by kovsu** [comment]
![Image](https://github.com/user-attachments/assets/a2cf6dd7-5325-4728-b088-edaa45e8b62b)

**Comment by kovsu** [comment]
https://github.com/nodejs/node/compare/master

https://github.com/nodejs/node/compare/master...master

https://github.com/nodejs/node/milestone/25

**Comment by kovsu** [comment]
- This link is swallowed: https://github.com

**Comment by kovsu** [comment]
- Related: #19 

## Spaces

```
 
  
  function() {}  
function  () {}
```

```js
 
  
  function() {}  
function  () {}
```

## Tabs


```
	
		
		function()	{}		
function		()	{}
```
```js
	
		
		function()	{}		
function		()	{}
```


## Mixed


```
	 
	 	 
 	 function() {} 	
function	 ()	{}
```

```js
	 
	 	 
 	 function() {} 	
function	 ()	{}
```

## Inlined

https://github.com/refined-github/sandbox/blob/d773f5944129a7e1fc1caca10009723d8bb70b5e/README.md?plain=1#L19-L28

## Real code

```js

function showWhiteSpacesOn(line: Element): void {
	const shouldAvoidSurroundingSpaces = Boolean(line.closest('.blob-wrapper-embedded')); // #2285
	const textNodesOnThisLine = getTextNodes(line);
	for (const [nodeIndex, textNode] of textNodesOnThisLine.entries()) {
		// `textContent` reads must be cached #2737
		let text = textNode.textContent!;
		if (text.length > 1000) { // #5092
			continue;
		}
```

**Comment by kovsu** [comment]
https://github.com/download-directory/download-directory.github.io/blob/main/.parcelrc

**Comment by injust** [comment]
@injust testing
