### ISSUE TITLE
Compresses All Files Without Including the Folder Name

### ISSUE THREAD

**Issue by Paulius11** [download-directory/download-directory.github.io#148]
If a folder in the repository is required, it gathers all the files but does not create the folder itself where the files should be placed.

**Current Behavior:**
All files are gathered in the root directory.

**Desired Behavior:**
Create the required root folder and place all the files within it.

**Comment by fregante** [comment]
You can extract the zip file into a folder to achieve the same result. On macOS for example that's the default behavior for extraction
