### ISSUE TITLE
Support for GitHub Enterprise 

### ISSUE THREAD

**Issue by aslafy-z** [download-directory/download-directory.github.io#28]
I'd love to download directories in my GHE instance. This should be doable!

**Comment by fregante** [comment]
The code changes for this would be minimal. 

The token just needs to be stored on a key that includes the domain entered, for example `token-www.GitHub.com` and `token-gh.example.com`

When the page loads with the URL to download, the token code will look for the domain-specific token and in case ask for a new one. 

PR welcome!

**Comment by suriyo-cycrones** [comment]
#41
