### ISSUE TITLE
Silently fails if token is missing

### ISSUE THREAD

**Issue by fregante** [download-directory/download-directory.github.io#39]
Example: https://download-directory.github.io/?url=https://github.com/phracker/MacOSX-SDKs/tree/master/MacOSX10.1.5.sdk

It used to ask for a token but I think this was recently disabled. Now it just doesn't do anything 😞

**Comment by kamekku14** [comment]
Why not add the ability to save the GitHub token via cookie storage\/JSON storage?

**Comment by fregante** [comment]
There’s already a field to save it to localStorage

**Comment by fregante** [comment]
I'm not sure this is the case anymore. The API is only used for private repos and for the very first 2 API calls, in which case it already suggests adding a token.

**Comment by fregante** [comment]
I'll reopen it because it should still handle the error, should this happen on the first request

**Comment by fregante** [comment]
<img width="755" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/217241054-abfb395c-d157-4d50-b556-cc8876b91dcc.png">
