### ISSUE TITLE
Can you **** the token?

### ISSUE THREAD

**Issue by yakov116** [download-directory/download-directory.github.io#4]
I think it would be best to hide the token after putting one in

**Comment by bfred-it** [comment]
Done. Will deploy whenever Travis starts working again 86db344e2cdc0425faa0d6da6db2ab08ded227d8

**Comment by sindresorhus** [comment]
> I think I will undo this. The token is just stored in localStorage and •••••• might give you the illusion that it's safe but it's not really

👍
