### ISSUE TITLE
"No files to download" on large repos

### ISSUE THREAD

**Issue by glzlaohuai** [download-directory/download-directory.github.io#41]
Download using this link: https://github.com/phracker/MacOSX-SDKs/tree/master/MacOSX10.14.sdk

It prompts: No files to download

**Comment by fregante** [comment]
Yeah this is a limit unfortunately, the repo is huge.

In this specific case, the repo also contains submodules which are definitely not supported and are unlikely to ever be.

**Comment by glzlaohuai** [comment]
Thanks for the clarification.

**Comment by fregante** [comment]
I think however we could show a better error message at least

**Comment by mattalexx** [comment]
It's a shame that it's the large repos that are affected, because that's usually precisely why I'm using an app like this instead of just cloning.

**Comment by kidonng** [comment]
@mattalexx that's probably the best solution.
@fregante Maybe the website can provide [commands to do a sparse checkout](https://stackoverflow.com/a/52269934) that is approximately equivalent to download the requested directory.
