### ISSUE TITLE
Git LFS support

### ISSUE THREAD

**Issue by friuns2** [download-directory/download-directory.github.io#42]
https://github.com/jgarside1678/T9/blob/master/Content/Units/Alliance/Animations/MageAnimationSet/Animations/InPlace/Mage_Beam_2h_End_IP.uasset

uasset files are empty

**Comment by fregante** [comment]
That'd it be great!

PR welcome https://gist.github.com/fkraeutli/66fa741d9a8c2a6a238a01d17ed0edc5#retrieving-lfs-files
