### ISSUE TITLE
Can we re-use your code for our open-source community?

### ISSUE THREAD

**Issue by hugoabernier** [download-directory/download-directory.github.io#43]
Hey @fregante, fantastic work!

I help manage an open-source community of over 1,300 active contributors with pretty large repos.

We'd love to give our community the ability to download only the subfolders they need, but we'd prefer to not overload your  site with extra traffic.

I saw that your code is MIT-licensed, but I wanted to ask for your permission to use your code in our community website -- while making sure to give you credit, of course.

If so, do you have any recommendations on how to get started?

**Comment by fregante** [comment]
> overload your site with extra traffic

The site is a plain HTML page served by GitHub, hence the github.io domain. The downloads are straight from the GitHub’s API, so there's no bandwidth issue at all, it can be used directly, ;) I don't pay a dime.

**Comment by hugoabernier** [comment]
Lol, I noticed. Great use of GitHub pages! 

Thanks @fregante  for the quick response!

Our plan is to use a snapshot of your code, but add code to package additional assets in the `.zip` file to help our community members (e.g.: extra instructions, etc.).

I've already changed the code in my fork to add "Thanks" to the page because you definitely deserve kudos for the nice and succinct code. I looked at [GitZip](https://kinolien.github.io/gitzip/) and [DownGit](https://minhaskamal.github.io/DownGit/), but I thought your code was cleaner.

Here's a screenshot of what it looks like:
![image](https://user-images.githubusercontent.com/13972467/140627071-bd3f948c-be5c-4ef4-ae10-ae23a6b2f23a.png)

So, you're ok with us sending people your way? As far as I'm concerned, everyone who uses GitHub should know about this repo 😋

**Comment by fregante** [comment]
Sure no problem. You can link to this repository rather than the website, because the website might not be clear (since it looks the same)

Glad you like it! I thought the same of those two websites, that's why I made this one. I hope to improve it a bit more in the future though.
