### ISSUE TITLE
Some files were blocked from downloading, try to disable any ad blockers and refresh the page."  

### ISSUE THREAD

**Issue by foxmajik** [download-directory/download-directory.github.io#50]
Always returns the error "Some files were blocked from downloading, try to disable any ad blockers and refresh the page."

I tried Chrome, Firefox and Edge all with all extensions/plug-ins disabled and pop-ups allowed.

**Comment by fregante** [comment]
Can you provide a URL that doesn't work?

**Comment by foxmajik** [comment]
I can't be f'd. I just went on and used a different tool.
