### ISSUE TITLE
Failed to Load Resource: ERR_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by Coy-Allen** [download-directory/download-directory.github.io#51]
The directory download fails for very large folders with error net::ERR_INSUFFICIENT_RESOURCES
![Capture](https://user-images.githubusercontent.com/22683505/149038179-accfd624-1a2f-428f-b947-60fee6982d51.PNG)

**Comment by fregante** [comment]
This will be fixed by https://github.com/download-directory/download-directory.github.io/pull/49
