### ISSUE TITLE
Handle API errors

### ISSUE THREAD

**Issue by fregante** [download-directory/download-directory.github.io#6]
404s are stuck on `Retrieving directory info…`

**Comment by fregante** [comment]
@loilo token-related issues are not caught. Try entering `00000000000000000000000000000000000` as the token, it will be stuck on `Retrieving directory info…`

**Comment by loilo** [comment]
Ha. I silently removed the frontend feedback for the "repo exists & is public" check when I removed the `.catch()` block from the `init()` call and handled everything in-place. Forgot to do that for this particular check. BRB with a new PR. 😁
