### ISSUE TITLE
Getting error "Some files were blocked from downloading, try to disable any ad blockers and refresh the page."

### ISSUE THREAD

**Issue by cmdcolin** [download-directory/download-directory.github.io#65]
using example from the webpage e.g.

https://download-directory.github.io/?url=https://github.com/mrdoob/three.js/tree/dev/build

Or my own

https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FGMOD%2Fjbrowse-components%2Ftree%2Fmain%2Fdemos%2Fjbrowse-react-linear-genome-view-vite

error in private tab, no adblocker extensions enabled afaik

**Comment by cmdcolin** [comment]
sorry about that it submitted issue before I was ready. updated original post but the example directory gives this as well as my own folders

e.g.

https://download-directory.github.io/?url=https://github.com/mrdoob/three.js/tree/dev/build

**Comment by fregante** [comment]
It’s possible that my last update broke it. I saw this error locally, I fixed something and then it worked. Now it seems there again?

**Comment by cmdcolin** [comment]
I think it is ok now:)

**Comment by cmdcolin** [comment]
maybe can close all now. thanks for your work on this, super handy!
