### ISSUE TITLE
Support private repos

### ISSUE THREAD

**Issue by fregante** [download-directory/download-directory.github.io#7]
1. token instructions don't include private repos
2. if enabled, files are still fetched without token, so they 404

**Comment by loilo** [comment]
Side note: I've taken a look on this, but this is currently technically impossible due to `raw.githubusercontent.com` returning 403 answers for `OPTIONS` requests. However, those requests are inevitably made by the browser as preflight requests when making authorized calls with a bearer token attached.

This problem has been reported to GitHub [relatively recently](https://github.community/t5/GitHub-API-Development-and/preflight-requests-to-raw-githubusercontent-com/m-p/32799) and at least they are aware.

However, until this changes, it will not be possible to do a purely client-side XHR request to private resources.

**Comment by loilo** [comment]
That said, file contents could still be fetched via the GitHub API.

@fregante What would be your shot at this? Would you wait for GitHub to change their CORS behavior or make requests to the GitHub API? I'd happily implement anything. 😄

**Comment by fregante** [comment]
> That said, file contents could still be fetched via the GitHub API.

The GitHub API is limited (filesize) so this change would break downloading some larger files.

> impossible due to `raw.githubusercontent.com` returning 403 answers for `OPTIONS` requests

When does this happen? How are you passing the authorization? Pre-flight doesn't happen if we use [simple requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests)

**Comment by loilo** [comment]
Pre-flight does happen though if we're trying to authorize with a bearer token. This seems to be the only working authentication mechanism for our case.

When private files are shown in the browser, GitHub appends a `token` GET parameter, however this does not seem to use regular access tokens — at least I'm getting 404 errors when I'm trying to use my access token in that place (and only there).

**Comment by fregante** [comment]
It looks like GitHub's own `raw` link includes a `token` parameter, generating a URL like:

```
https://raw.githubusercontent.com/mrdoob/three.js/dev/build/three.js?token=000000000
```

However if I try to plug _my_ token in, it returns a 404 (i.e. unauthorized on private repos)

**Comment by fregante** [comment]
> This seems to be the only working authentication mechanism for our case.

Yeah, HTTP authentication via URL and `XMLHttpRequest.open` doesn't seem to be supported anymore. `curl https://token@raw.etc/file.ext` works but not in the browser.

**Comment by fregante** [comment]
What do you think about implementing the API as a fallback for private repos? I think it'd have to check whether all the files are under 1MB as well; thankfully this info is available in the `list` API call.

**Comment by loilo** [comment]
Sounds good to me. Going to take a look soon — got another PR regarding error handling to land first (i.e. in a few seconds, be prepared 😁).

**Comment by fregante** [comment]
`list-github-dir-content` exists only because of `download-directory.github.io`. Since it doesn't have tests, `download-directory.github.io` serves as a "live test."

In short, I'd extend it rather than copy it here.

---

If you want to send a PR there, we could add a flag to get the whole file object instead of just the path

```diff
- files.push(item.path);
+ if (getWholeData) {
+ 	files.push(item);
+ } else {
+ 	files.push(item.path);
+ }
```

Thoughts?

---

With a new flag however I'd suggest changing its API(s) to:

```js
viaTreesApi({
	user: '',
	repository: '',
	ref: '',
	directory: '',
	token: '',

	getWholeData: false // new, name TBD
})
```

**Comment by loilo** [comment]
Exactly how I'd have done it, nice. Going to submit a PR. Suggested names: `details`, `includeDetails`, `includeMetadata`.

**Comment by loilo** [comment]
I don't like either of my suggestions. `detailed` is not self-explaining enough IMO and all of the others indicate that metadata is sent *alongside* the file names, not in their place.
