### ISSUE TITLE
Cannot download when filename contains hash (#)

### ISSUE THREAD

**Issue by Tsuk1ko** [download-directory/download-directory.github.io#74]
Is URI encode missing?

**Comment by fregante** [comment]
Can you give an example of URL you're pasting?

**Comment by Tsuk1ko** [comment]
https://github.com/Tsuk1ko/download-directory-issue-demo/tree/main/failed

There is a file `1#1.txt` in this folder.

Download URL: https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FTsuk1ko%2Fdownload-directory-issue-demo%2Ftree%2Fmain%2Ffailed

![image](https://user-images.githubusercontent.com/24877906/189324054-05234aac-8f4a-498e-ba45-2b08600ed5ae.png)

**Comment by Tsuk1ko** [comment]
I noticed that it is trying to download

```
https://raw.githubusercontent.com/Tsuk1ko/download-directory-issue-demo/main/failed/1#1.txt
```

But the correct URL should be

```
https://raw.githubusercontent.com/Tsuk1ko/download-directory-issue-demo/main/failed/1%231.txt
```
