### ISSUE TITLE
Filenames starting with "ad" are blocked by ad-blockers

### ISSUE THREAD

**Issue by sindresorhus** [download-directory/download-directory.github.io#9]
This one has 261 files and it stops at 260: https://download-directory.github.io/?url=https://github.com/cjdowner/cryptocurrency-icons/tree/master/svg/color

**Comment by bfred-it** [comment]
That's hilarious.

This file is consistently failing to load:

<img width="493" alt="adx.svg" src="https://user-images.githubusercontent.com/1402241/37507712-8e8975a6-2922-11e8-982b-2845c31f78cc.png">

And you know why?

It starts with `ad`

**Comment by bfred-it** [comment]
Course of action:

1. https://github.com/download-directory/download-directory.github.io/issues/6
2. Suggest disabling ad block on site
