### ISSUE TITLE
File System Access API support

### ISSUE THREAD

**Issue by topjohncian** [download-directory/download-directory.github.io#94]
We can download directories without zipping using the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API).

I'd like to implement this feature. 😆

**Comment by fregante** [comment]
Thank you for the offer! I have a couple of questions:

- can that API actually create multiple files at once?
- why abandon the zip? What’s the advantage? On macOS zip files are automatically extracted on download and the folder appears in their place. Also there’s no “save as” dialog so it’s effectively zero-clicks to download a folder

**Comment by topjohncian** [comment]
Thank you for your reply!
1. Sorry I have doubts about your first question. 😢 Could you please describe it more? You can open [it](https://demo.cloudreve.org/s/xXrJtP), right-click, click `Download` to see the effect.
2. Using the API there's also a step of creating the directory and submitting in the "save as" dialog. It seems to me that it can be set as an optional feature.

**Comment by fregante** [comment]
As I feared, it's only possible by granting access to whole folder, which is super bad UX:

<img width="531" alt="Screenshot 1" src="https://github.com/download-directory/download-directory.github.io/assets/1402241/7b58bf70-de93-477d-a56e-86ba8f0bfbb7">


macOS doesn't even allow this for the Downloads folder:

<img width="532" alt="Screenshot" src="https://github.com/download-directory/download-directory.github.io/assets/1402241/c98f3630-24e2-45f0-a0b4-2ca39843240b">




> 2\. it can be set as an optional feature

It doesn't offer enough benefits to justify this being an option. I suppose it would improve support for super large files but those are rarely found in a git repo to begin with
