### ISSUE TITLE
Download of subfolder contains parent folder

### ISSUE THREAD

**Issue by PhantomGamers** [download-directory/download-directory.github.io#98]
When using this website to download the folder [AikoMidori/SteamSkins/tree/main/Metro/Metro-JS/](https://github.com/AikoMidori/SteamSkins/tree/main/Metro/Metro-JS/), the resulting zip has the structure of `Metro/Metro-JS/`, whereas I would expect it to just have `Metro-JS` in the root.

Is this intended behavior or a bug? If this is intended behavior, could there be some way to change this with an argument passed?

**Comment by fregante** [comment]
I don’t remember this being an issue, are you on Windows?

**Comment by PhantomGamers** [comment]
> I don’t remember this being an issue, are you on Windows?

Yes, I'm on Windows 11 and the issue happens on both Firefox and Edge.

> This works correctly on iOS, the ZIP file seems to contain the raw contents of the folder, 5 files:
> 
>     * [download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Frefined-github%2Frefined-github%2Ftree%2Fmain%2Fsource%2Fgithub-events](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Frefined-github%2Frefined-github%2Ftree%2Fmain%2Fsource%2Fgithub-events)

Yes, if I just put the folder link directly it has that behavior, but I do want the folder itself to be in the root of the zip file so I append `/` to the url.

For example:

`https://download-directory.github.io/?url=https://github.com/AikoMidori/SteamSkins/tree/main/Metro` produces a zip file that contains all of the files in the Metro folder in the root of the zip

`https://download-directory.github.io/?url=https://github.com/AikoMidori/SteamSkins/tree/main/Metro/` produces a zip file that contains a `Metro` folder that then contains all of the files.

However `https://download-directory.github.io/?url=https://github.com/AikoMidori/SteamSkins/tree/main/Metro/Metro-JS/` produces a zip file that contains `Metro/Metro-JS`

**Comment by fregante** [comment]
Heh, this is *undefined behavior*. The fact that it behaves differently is a big as both URLs point to the same resource. In both cases the result should be the one I showed earlier. 

Changing the zip’s structure is out of scope as the zip is just the current vessel to “download a directory” and may change at any time. See for example #94

**Comment by PhantomGamers** [comment]
In my opinion the current behavior generally makes sense, with / indicating that you want the folder itself being included, but I'll just fork this and fix that issue myself then if this feature is not in the scope of this project.

**Comment by fregante** [comment]
@PhantomGamers feel free to send a PR to add a search parameter to toggle this line:

https://github.com/download-directory/download-directory.github.io/blob/406e9b7f1e3c1ae9106b1bad588ad94650e83d62/index.ts#L233

Something like: `search.has('keep-path') ? file.path : file.path.replace(directory + '/', '')`

It should also be documented in the readme

**Comment by fregante** [comment]
Perhaps:

- `path=full` with your behavior
- `path=flat` would match [--junk-paths](https://stackoverflow.com/a/72282401/288906), storing the files without path information
- the default is what we have currently
